LIBRARY ieee;
USE ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

LIBRARY work;

ENTITY VGA_TOP IS 
	PORT
	(
		CLK     : IN  STD_LOGIC;
		CLKM    : IN  STD_LOGIC;
		RESET_n : IN  STD_LOGIC;

		CSR     : IN  STD_LOGIC;
		CSM     : IN  STD_LOGIC;
		MEM16   : IN  STD_LOGIC;
		A       : IN  STD_LOGIC_VECTOR(18 DOWNTO 0);
		D       : IN  STD_LOGIC_VECTOR(15 DOWNTO 0);

		MD      : INOUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		MA      : OUT STD_LOGIC_VECTOR(17 DOWNTO 0);
		MWE     : OUT STD_LOGIC;
		MOE     : OUT STD_LOGIC;
		MBLE    : OUT STD_LOGIC;
		MBHE    : OUT STD_LOGIC;

		COLOR	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);

--		RGB	: OUT STD_LOGIC_VECTOR(17 DOWNTO 0);

		HSYNC   : OUT STD_LOGIC;
		VSYNC   : OUT STD_LOGIC;
		BLANK   : OUT STD_LOGIC
	);
END;

ARCHITECTURE bdf_type OF VGA_TOP IS 

component SYNCH
	PORT
	(
		CLK     :  IN STD_LOGIC;
		RESET_n :  IN STD_LOGIC;

		H       : OUT STD_LOGIC_VECTOR(11 DOWNTO 0);
		V       : OUT STD_LOGIC_VECTOR(11 DOWNTO 0);

		HACTIVE : OUT STD_LOGIC;
		VACTIVE : OUT STD_LOGIC;

		ANIMAT  : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);

		HSYNC   : OUT STD_LOGIC;
		VSYNC   : OUT STD_LOGIC;
		BLANK   : OUT STD_LOGIC
	);
END component;

component VGA_REGS
	PORT
	(
		CLK     : IN  STD_LOGIC;
		RESET_n : IN  STD_LOGIC;

		CSR     : IN  STD_LOGIC;
		CSM     : IN  STD_LOGIC;
		MEM16   : IN  STD_LOGIC;
		A       : IN  STD_LOGIC_VECTOR(18 DOWNTO 0);
		D       : IN  STD_LOGIC_VECTOR(15 DOWNTO 0);

		CONTROL : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
		HSCROLLM: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		VSCROLLM: OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
		HSCROLLS: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		VSCROLLS: OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
		HSCROLLB: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		VSCROLLB: OUT STD_LOGIC_VECTOR(6 DOWNTO 0);

		HCURSOR : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
		VCURSOR : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);

		M_SPLIT0: OUT STD_LOGIC_VECTOR(5 DOWNTO 0);
		M_SPLIT1: OUT STD_LOGIC_VECTOR(6 DOWNTO 0);

		S_SPLIT0: OUT STD_LOGIC_VECTOR(5 DOWNTO 0);
		S_SPLIT1: OUT STD_LOGIC_VECTOR(6 DOWNTO 0);

		B_SPLIT0: OUT STD_LOGIC_VECTOR(5 DOWNTO 0);
		B_SPLIT1: OUT STD_LOGIC_VECTOR(6 DOWNTO 0);

		MSEL    :  IN STD_LOGIC;
		MDo     : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		MA      : OUT STD_LOGIC_VECTOR(17 DOWNTO 0);
		MWE     : OUT STD_LOGIC;
		MBLE    : OUT STD_LOGIC;
		MBHE    : OUT STD_LOGIC
	);
END component;

component VGA
	PORT
	(
		CLK	:  IN STD_LOGIC;
		CLKM    :  IN STD_LOGIC;
		RESET_n	:  IN STD_LOGIC;

		CONTROL	:  IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		HSCROLLM:  IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		VSCROLLM:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);
		HSCROLLS:  IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		VSCROLLS:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);
		HSCROLLB:  IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		VSCROLLB:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);
		HCURSOR	:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);
		VCURSOR	:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);

		M_SPLIT0:  IN STD_LOGIC_VECTOR(5 DOWNTO 0);
		M_SPLIT1:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);

		S_SPLIT0:  IN STD_LOGIC_VECTOR(5 DOWNTO 0);
		S_SPLIT1:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);

		B_SPLIT0:  IN STD_LOGIC_VECTOR(5 DOWNTO 0);
		B_SPLIT1:  IN STD_LOGIC_VECTOR(6 DOWNTO 0);

		BLANK	:  IN STD_LOGIC;

		H       :  IN STD_LOGIC_VECTOR(11 DOWNTO 0);
		V       :  IN STD_LOGIC_VECTOR(11 DOWNTO 0);

		ANIMAT	:  IN STD_LOGIC_VECTOR(3 DOWNTO 0);

		M_COLOR	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);
		S_COLOR	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);
		B_COLOR	: OUT STD_LOGIC_VECTOR(5 DOWNTO 0);

		MSEL	: OUT STD_LOGIC;
		MA	: OUT STD_LOGIC_VECTOR(17 DOWNTO 0);
		MDi	:  IN STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END component;

component VGA_PAL
	PORT
	(
		CLK	: IN  STD_LOGIC;
		RESET_n	: IN  STD_LOGIC;

		CS	: IN  STD_LOGIC;
		A	: IN  STD_LOGIC_VECTOR(1 DOWNTO 0);
		D	: IN  STD_LOGIC_VECTOR(7 DOWNTO 0);

		M_COLOR	: IN  STD_LOGIC_VECTOR(8 DOWNTO 0);
		S_COLOR	: IN  STD_LOGIC_VECTOR(8 DOWNTO 0);
		B_COLOR	: IN  STD_LOGIC_VECTOR(5 DOWNTO 0);

		SP_COLOR: IN  STD_LOGIC_VECTOR(7 DOWNTO 0);

		COLOR	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);
		RGB	: OUT STD_LOGIC_VECTOR(17 DOWNTO 0)
	);
END component;

SIGNAL	H       : STD_LOGIC_VECTOR(11 DOWNTO 0);
SIGNAL	V       : STD_LOGIC_VECTOR(11 DOWNTO 0);
SIGNAL	ANIMAT  : STD_LOGIC_VECTOR(3 DOWNTO 0);

SIGNAL	HACTIVE : STD_LOGIC;
SIGNAL	VACTIVE : STD_LOGIC;
SIGNAL	BLANKo  : STD_LOGIC;

SIGNAL	CONTROL : STD_LOGIC_VECTOR(31 DOWNTO 0);
SIGNAL	HSCROLLM: STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	VSCROLLM: STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	HSCROLLS: STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	VSCROLLS: STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	HSCROLLB: STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	VSCROLLB: STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	HCURSOR : STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	VCURSOR : STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	M_SPLIT0: STD_LOGIC_VECTOR(5 DOWNTO 0);
SIGNAL	M_SPLIT1: STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	S_SPLIT0: STD_LOGIC_VECTOR(5 DOWNTO 0);
SIGNAL	S_SPLIT1: STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	B_SPLIT0: STD_LOGIC_VECTOR(5 DOWNTO 0);
SIGNAL	B_SPLIT1: STD_LOGIC_VECTOR(6 DOWNTO 0);

SIGNAL	MA_S    : STD_LOGIC_VECTOR(17 DOWNTO 0);
SIGNAL	MA_R    : STD_LOGIC_VECTOR(17 DOWNTO 0);
SIGNAL	MA_V    : STD_LOGIC_VECTOR(17 DOWNTO 0);
SIGNAL	MDi     : STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	MDo     : STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	M_LE    : STD_LOGIC;
SIGNAL	M_HE    : STD_LOGIC;
SIGNAL	MSEL    : STD_LOGIC;

SIGNAL	M_COLOR	: STD_LOGIC_VECTOR(8 DOWNTO 0);
SIGNAL	S_COLOR	: STD_LOGIC_VECTOR(8 DOWNTO 0);
SIGNAL	B_COLOR	: STD_LOGIC_VECTOR(5 DOWNTO 0);
SIGNAL	SP_COLOR: STD_LOGIC_VECTOR(7 DOWNTO 0) := "00000000";

SIGNAL	MREQ : STD_LOGIC;
SIGNAL	MRDY : STD_LOGIC;

BEGIN 

SYN: SYNCH
	PORT MAP(CLK, RESET_n, H, V, HACTIVE, VACTIVE, ANIMAT, HSYNC, VSYNC, BLANKo);

REG: VGA_REGS
	PORT MAP(CLK, RESET_n, CSR, CSM, MEM16, A, D,
		CONTROL, HSCROLLM, VSCROLLM, HSCROLLS, VSCROLLS, HSCROLLB, VSCROLLB,
		HCURSOR, VCURSOR, M_SPLIT0, M_SPLIT1, S_SPLIT0, S_SPLIT1, B_SPLIT0, B_SPLIT1,
		MSEL, MDo, MA_V, MWE, M_LE, M_HE);

V0: VGA
	PORT MAP(CLK, CLKM, RESET_n,
		CONTROL, HSCROLLM, VSCROLLM, HSCROLLS, VSCROLLS,  HSCROLLB, VSCROLLB,
		HCURSOR, VCURSOR, M_SPLIT0, M_SPLIT1, S_SPLIT0, S_SPLIT1, B_SPLIT0, B_SPLIT1,
		BLANKo, H, V, ANIMAT,
		M_COLOR, S_COLOR, B_COLOR,
		MSEL, MA_R, MDi);

PAL: VGA_PAL
	PORT MAP(CLK, RESET_n, CSR, A(1 DOWNTO 0), D(7 DOWNTO 0),
		M_COLOR, S_COLOR, B_COLOR, SP_COLOR,
		COLOR);

MA  <= MA_V  WHEN MSEL = '1' ELSE MA_R;
MD  <= MDo   WHEN MSEL = '1' ELSE (OTHERS => 'Z');
MBLE <= M_LE WHEN MSEL = '1' ELSE '0';
MBHE <= M_HE WHEN MSEL = '1' ELSE '0';
MDi <= MD;
MOE <= MSEL;

BLANK <= BLANKo;

END;
